spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: oracle.jdbc.OracleDriver
    druid:
        url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true


