spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: oracle.jdbc.OracleDriver
    druid:
        url: jdbc:oracle:thin:@192.168.123.119:1521:orcl
        username: ecif
        password: 123456
        driverClassName: oracle.jdbc.OracleDriver
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true


