#指定启动端口
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#指定log配置
logging:
  config: ${loggingConfig:classpath:log4j2.xml}
  level:
     edsp:
         dao: DEBUG
         transport: DEBUG
     cn.sunline.crm.provider.mapper: DEBUG
  path: ./logs
file:
  encoding: utf-8

#==============####jdbc配置==============####
spring:
  application:
    name: service-provider

mybatis:
  #实体类存放路径
  type-aliases-package: cn.sunline.example.entity
  mapper-locations: classpath:mapper/*.xml
#==============事务配置==============
#execution(* cn.sunline..*Service.*(..)) or execution(* cn.xxxx..*Service.*(..))#######
aop:
  pointcut:
    expression: execution(* cn.sunline..*Service.*(..))

#==============生成API文档==============
swagger:
  enabled: true
  basePackage: cn.sunline.edsp.samples.controller     #扫描的包名
  title:  edsp
  contact: SUNLINE
  version: 1.0.0


