eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: feigndemo
  boot:
    admin:
      client:
        url: http://localhost:8084
feign:
  hystrix:
    enabled: true
