eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766

spring:
  application:
    name: feigndemo
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  boot:
    admin:
      client:
        url: http://localhost:8084
feign:
  hystrix:
    enabled: true
