eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spring-cloud-service-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
      port: 8762